In [14]:
import pandas as pd
import numpy as np
# https://www.sciencedirect.com/science/article/pii/S228843001630149X

In [17]:
def encode_haar_2d(inputs):
  inputs_len = len(inputs)
  outputs = np.zeros(shape=(inputs_len,inputs_len))
  while(inputs_len > 1):
    inputs_len_half = inputs_len // 2
    for x in range(inputs_len_half):
      index_x = x * 2
      for y in range(inputs_len_half):
        index_y = y * 2
        values = inputs[index_x:index_x+2,index_y:index_y+2]
        outputs[x,y] = (inputs[index_x][index_y] + inputs[index_x+1][index_y+1] + inputs[index_x+1][index_y] + inputs[index_x][index_y+1]) / 4
        outputs[x+inputs_len_half,y+inputs_len_half] = (inputs[index_x][index_y] + inputs[index_x+1][index_y+1] - inputs[index_x+1][index_y] - inputs[index_x][index_y+1]) / 4
        outputs[x,y+inputs_len_half] = (inputs[index_x][index_y] + inputs[index_x+1][index_y] - inputs[index_x+1][index_y+1] - inputs[index_x][index_y+1]) / 4
        outputs[x+inputs_len_half,y] = (inputs[index_x][index_y] + inputs[index_x][index_y+1] - inputs[index_x+1][index_y] - inputs[index_x+1][index_y+1]) / 4
    inputs = outputs[:inputs_len_half,:inputs_len_half].copy()
    inputs_len = len(inputs)
  return outputs

In [18]:
inputs = np.array([[70,56,61,49],
          [52,46,39,43],
          [63,45,46,54],
          [53,39,40,44]])
encode_haar_2d(inputs)

[[56. 48.  5.  2.]
 [50. 46.  8. -3.]
 [ 7.  7.  2.  4.]
 [ 4.  4.  1. -1.]]
[[50.  3.  5.  2.]
 [ 2.  1.  8. -3.]
 [ 7.  7.  2.  4.]
 [ 4.  4.  1. -1.]]


array([[50.,  3.,  5.,  2.],
       [ 2.,  1.,  8., -3.],
       [ 7.,  7.,  2.,  4.],
       [ 4.,  4.,  1., -1.]])

In [19]:
def decode_haar_2d(inputs):
    inputs_len = len(inputs)
    outputs = inputs.copy()
    
    current_len = 1
    while(inputs_len > current_len):
        decoding = np.zeros(shape=(current_len*2,current_len*2))
        for x in range(current_len):
            output_idx_x = x * 2
            for y in range(current_len):
                output_idx_y = y * 2
                decoding[output_idx_x,output_idx_y] = outputs[x,y] + outputs[x,y+current_len] + outputs[x+current_len,y] + outputs[x+current_len,y+current_len]
                decoding[output_idx_x,output_idx_y+1] = outputs[x,y] + outputs[x+current_len,y] - outputs[x,y+current_len] - outputs[x+current_len,y+current_len]
                decoding[output_idx_x+1,output_idx_y] = outputs[x,y] + outputs[x,y+current_len] - outputs[x+current_len,y] - outputs[x+current_len,y+current_len]
                decoding[output_idx_x+1,output_idx_y+1] = outputs[x,y] + outputs[x+current_len,y+current_len] - outputs[x+current_len,y] - outputs[x,y+current_len] 
        current_len = current_len * 2
        outputs[:current_len,:current_len] = decoding.copy()
    return outputs 

In [20]:
inputs = np.array(
    [[50,3,5,2],
    [2,1,8,-3],
    [7,7,2,4],
    [4,4,1,-1]])
decode_haar_2d(inputs)

array([[70, 56, 61, 49],
       [52, 46, 39, 43],
       [63, 45, 46, 54],
       [53, 39, 40, 44]])